---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-armada
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.armada
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.ucp.armada
      dest:
        path: .values.images.tags

    # Endpoints
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.identity
      dest:
        path: .values.endpoints.identity
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.armada
      dest:
        path: .values.endpoints.armada

    # Credentials
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.keystone.admin
      dest:
        path: .values.endpoints.identity.auth.admin
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.armada.keystone
      dest:
        path: .values.endpoints.identity.auth.user

    # Secrets
    - dest:
        path: .values.endpoints.identity.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_keystone_admin_password
        path: .
    - dest:
        path: .values.endpoints.identity.auth.user.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_armada_keystone_password
        path: .
data:
  chart_name: armada
  release: ucp-armada
  namespace: ucp
  timeout: 100
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    replicas:
      api: 1
    armada:
      DEFAULT:
        debug: true
    manifests:
      deployment_tiller: false
      service_tiller: false
  dependencies:
    - armada-htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: armada-htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.armada-htk
      dest:
        path: .source
data:
  chart_name: armada-htk
  release: armada-htk
  namespace: armada-htk
  timeout: 100
  values: {}
  dependencies: []
...
